name: zurich
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  shelf_static: ^1.1.2
  shelf_router: ^1.1.4
  path_provider: ^2.1.5
  shelf: ^1.4.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  network_ap:
    path: ../network_ap

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/browser/
    - assets/browser/create/
    - assets/browser/other/
